apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolrental-deployment
  labels:
    app: toolrental
spec:
  replicas: 2
  selector:
    matchLabels:
      app: toolrental
  template:
    metadata:
      labels:
        app: toolrental
    spec:
     containers:
      - name: toolrental-container
        image: cedricassemien/toolrental:latest 
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "ToolRental.settings"
        - name: ALLOWED_HOSTS
          value: "*"
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"